import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
import urllib.request
import pandas as pd
import json

url = 'http://ncov.mohw.go.kr/'

response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

table = soup.find("ul", class_ = "liveNum")
table1 = table.find_all('span', class_ = 'num')
data=[]
for i in range(0, len(table1)) :
    a = table1[i].get_text()
    data.append(a)
    
before = table.find("span", class_ = 'before')
before = before.get_text()
before = before.replace('전일대비 (+ ','')
before = before.replace(')','')

from datetime import date
today = date.today()
day = today.strftime(f"{today.month}/{today.day}")

data[0] = data[0].replace('(누적)','')
tot = []
tot.append(day)
tot.append(int(data[0].replace(',','')))
tot.append(int(before.replace(',','')))
tot.append(int(data[3].replace(',','')))
tot.append(int(data[1].replace(',','')))
tot

with open('koreacrawl.js', 'r', encoding='UTF-8-sig') as f:
    data = json.load(f)
    
if data[len(data)-1][0] == day :
    with open('koreacrawl.js', 'r', encoding = 'UTF-8-sig') as f:
        data = json.load(f)
else : 
    data.append(tot)
    with open('koreacrawl.js', 'w', encoding = 'UTF-8-sig') as f:
        json.dump(data, f, indent = '\t')
        
with open('koreacrawling.js', 'w', encoding='UTF-8-sig') as f :
    json.dump(data, f, indent = '\t')

data = ''
with open("koreacrawling.js", "r", encoding='UTF-8-sig') as f:    
    while True:
        line = f.readline()
        if not line: break
        data += line
data = '//Auto-generated by Korea.py\nvar koreanData = ' + data + ';'

with open("koreacrawling.js", "w", encoding='UTF-8-sig') as f_write:
    f_write.write(data)
data
